### PR TITLE
if a ca store isn't defined, use `:public_key` as a sane default

### PR DESCRIPTION
**Pull request by joshk**

### CODE REVIEW

**Comment by joshk** [comment]
if https://github.com/nerves-hub/nerves_hub_link/pull/166 is accepted then I'll update this PR to match

**Comment by joshk** [comment]
although, upon thinking about it, since `CAStore` is a dep, maybe just using that as the fallback is a fine default.

**Comment by jjcarstens** [comment]
I think that would be fine. The CLI is a local host tool. CAStore will probably satisfy most every setup, but also host systems typically have some large CAstore in `/etc/ssl` automagically which would be found with `:public_key.cacerts_get()`. We could make `CAStore` and optional dependency and if its not there, look at the system

**Comment by joshk** [comment]
I tend to agree with your approach. This would mean also updating `nerves_hub_link` so that `CAStore` is an optional dep there too, are you happy with me making that change?
Is marking the dep as `:optional` enough?

**Comment by jjcarstens** [comment]
Yep. Any user of `nerves_hub_link` would need to have the `castore` dep in the mix.exs explicitly. This is a better approach anyway for any users who are trying to save bytes and storage space

**Review by jjcarstens — APPROVED** [review]

**Pull request merged**
