### PR TITLE
Add task to export signing keys and certs.

### LINKED ISSUE #10: Export firmware signing keys
Add a command to export the private signing key. Currently, it's locked in a password-protected envelope which is great, but it's not usable outside of the `mix` tooling. Actually, if it is usable outside of `mix` by using some other Unix-y programs, then I think it's sufficient for my purposes to just document that.

### PR DESCRIPTION
**Pull request by ConnorRigby**
This task will allow exporting of both user certs and fwup signing keys.

Fixes #10

### CODE REVIEW

**Comment by mobileoverlord** [comment]
I think I would rather allow exporting at the module level. For example, I would make the tasks
`mix nerves_hub.key export KEY_NAME`
and
`mix nerves_hub.user cert export`

**Comment by ConnorRigby** [comment]
I was thinking this also. :+1: i'll update.

**Comment by ConnorRigby** [comment]
@mobileoverlord I split into the modules. i did `export_cert` instead of `cert export`. I'm not sure how i feel about it. What do you think?

**Comment by mobileoverlord** [comment]
I was thinking `cert export` for consistency with the cert task style already in `device`
https://github.com/nerves-hub/nerves_hub_cli/blob/master/lib/mix/tasks/nerves_hub.device.ex#L38-L56

**Comment by ConnorRigby** [comment]
Okay @mobileoverlord I believe this is ready, unless you have any more changes you'd like

**Pull request merged**
